services:
    study_app.domain.gnavi.config.api.config:
        class: StudyApp\Domain\Gnavi\Config\ApiConfig
        arguments: []
        calls:
            - ["init", []]

    study_app.domain.gnavi.service.api.service:
        class: StudyApp\Domain\Gnavi\Service\GnaviApiService
        arguments: ["@study_app.domain.gnavi.config.api.config"]
