services:
    study_app.factory.gnavi.area.code.maneger:
        class: StudyApp\CoreBundle\Factory\GnaviAreaCodeManeger
        arguments: []
        calls:
            - ["setContainer", ["@service_container"]]
    study_app.area.master.s:
        class: StudyApp\CoreBundle\Api\Master\AreaS
        arguments: []
